version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
    env_file: ./server/.env
    depends_on:
      - db
  
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  client:
    build: ./client
    ports:
      - "5173:5173"
    env_file: ./client/.env
    depends_on:
      - server
  
volumes:
  postgres_data: